language: objective-c
osx_image: xcode9.0
xcode_sdk: iphonesimulator11.0
script:
    - xcodebuild clean test -workspace Carrot.xcworkspace -scheme Carrot -destination "platform=iOS Simulator,name=iPhone X,OS=11.0" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
